services:
  se8350_controller:
    build: ./se8350_controller
    container_name: se8350_controller
    hostname: se8350_controller
    ports:
      - "47808:47808/udp"
    environment:
      - DEVICE_ID=1
      - OBJECT_NAME=SE8350_Room_Controller
      - VENDOR_ID=65530
    networks:
      bacnet_network:
        ipv4_address: 172.25.0.2

  cas_bacnet_stack_server:
    build: ./cas_bacnet_stack_server
    container_name: cas_bacnet_stack_server
    hostname: cas_bacnet_stack_server
    ports:
      - "47809:47808/udp"
    environment:
      - DEVICE_ID=2
      - OBJECT_NAME=CAS_Bacnet_Stack_Server
      - VENDOR_ID=65530
    networks:
      bacnet_network:
        ipv4_address: 172.25.0.3

networks:
  bacnet_network:
    name: bacnet_network
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16